export const GAME_CONSTANTS = {
  MAP_WIDTH: 20,
  MAP_HEIGHT: 20,
  GRASS_ENCOUNTER_CHANCE: 0.15,
  MAX_AREAS: 5,
  SAVE_DEBOUNCE_MS: 500,
  NOTIFICATION_DURATION_MS: 3000,
  TRAINER_ENGAGEMENT_DELAY_MS: 1500,
  TRANSITION_Y: 10,
};
