export const GAME_CONSTANTS = {
  MAP_WIDTH: 100,
  MAP_HEIGHT: 100,
  GRASS_ENCOUNTER_CHANCE: 0.15,
  MAX_AREAS: 9,
  SAVE_DEBOUNCE_MS: 500,
  NOTIFICATION_DURATION_MS: 3000,
  TRAINER_ENGAGEMENT_DELAY_MS: 1500,
  TRAINER_DIALOG_DELAY_MS: 500,
  TRANSITION_Y: 10,
  MOBILE_MOVEMENT_REPEAT_MS: 150,
};

export const SOUND_EFFECTS = {
  CLICK: 'click',
  HIT: 'hit',
  FAINT: 'faint',
  HEAL: 'heal',
  CAPTURE_SUCCESS: 'capture-success',
  CAPTURE_FAIL: 'capture-fail',
  BATTLE_START: 'battle-start',
  VICTORY: 'victory',
  LEVEL_UP: 'level-up',
  EVOLUTION: 'evolution',
  DISCOVERY: 'discovery',
};

/**
 * Pacing and animation durations (in milliseconds).
 * Note: Some values should align with CSS animation durations in BattleView.vue
 * - SHAKE_MS: Total shake duration (CSS: shake is 0.1s infinite, this gates the state)
 * - FLASH_MS: Screen flash duration (CSS: flash is 0.1s x 5 = 0.5s)
 * - CAPTURE_PROCESS_MS: Time from ball throw to result (CSS: capture is 0.5s)
 */
export const ANIMATION_DURATIONS = {
  SHAKE_MS: 500,
  FLASH_MS: 500,
  CAPTURE_PROCESS_MS: 1500,
  BATTLE_END_DELAY_MS: 3000,
  VICTORY_SOUND_DELAY_MS: 1000,
  CAPTURE_END_DELAY_MS: 2000,
  EVOLUTION_DURATION_MS: 4000,
  AI_SPELLING_DURATION_MS: 1000,
  AI_THROWN_WORD_DURATION_MS: 1500,
  POISON_FLASH_DURATION_MS: 300,
};

export const BATTLE_TYPES = {
  WILD: 'wild',
  TRAINER: 'trainer',
};

export const BATTLE_PHASES = {
  START: 'start',
  SELECT_ACTION: 'select_action',
  SELECT_MOVE: 'select_move',
  SPELLING: 'spelling',
  PLAYER_ATTACK: 'player_attack',
  ENEMY_TURN: 'enemy_turn',
  SWITCHING: 'switching',
  END: 'end',
  RESULTS: 'results',
  WHITED_OUT: 'whited_out',
  PARTY_FULL_REPLACE: 'party_full_replace',
  LEARN_MOVE: 'learn_move',
};

export const GENDERS = {
  BOY: 'Boy',
  GIRL: 'Girl',
};

export const SKIN_TONES = {
  PALE: 'pale',
  FAIR: 'fair',
  NEUTRAL: 'neutral',
  TAN: 'tan',
  DARK: 'dark',
};

export const INPUT_CONTEXTS = {
  WORLD: 'world',
  BATTLE: 'battle',
  MENU: 'menu',
  GLOBAL: 'global',
  MODAL: 'modal',
};

export const INPUT_PRIORITIES = {
  GLOBAL: 100,
  MODAL: 80,
  MENU: 50,
  BATTLE: 40,
  WORLD: 10,
};

export const BIOMES = {
  WILDERNESS: 'wilderness',
  CAVE: 'cave',
  TOWN: 'town',
  ROUTE: 'route',
  FOREST: 'forest',
};

export const TRANSITION_TYPES = {
  PREV: 'prev',
  NEXT: 'next',
};

export const MONSTER_TYPES = {
  NORMAL: 'Normal',
  FIRE: 'Fire',
  WATER: 'Water',
  GRASS: 'Grass',
  ELECTRIC: 'Electric',
  ICE: 'Ice',
  FIGHTING: 'Fighting',
  POISON: 'Poison',
  GROUND: 'Ground',
  FLYING: 'Flying',
  PSYCHIC: 'Psychic',
  BUG: 'Bug',
  ROCK: 'Rock',
  GHOST: 'Ghost',
  DRAGON: 'Dragon',
};

export const MOVE_CATEGORIES = {
  PHYSICAL: 'Physical',
  SPECIAL: 'Special',
  STATUS: 'Status',
};

export const MOVE_EFFECT_TYPES = {
  STAT_DOWN: 'STAT_DOWN',
  STAT_UP: 'STAT_UP',
  STATUS: 'STATUS',
  HEAL: 'HEAL',
  DRAIN: 'DRAIN',
  RECOIL: 'RECOIL',
  FIXED: 'FIXED',
};

export const STATUS_CONDITIONS = {
  NONE: 'NONE',
  POISON: 'POISON',
  PARALYSIS: 'PARALYSIS',
  SLEEP: 'SLEEP',
  BURN: 'BURN',
  FREEZE: 'FREEZE',
  CONFUSION: 'CONFUSION',
};

export const MOVE_IDS = {
  Absorb: 'Absorb',
  Acid: 'Acid',
  AcidArmor: 'AcidArmor',
  Agility: 'Agility',
  Amnesia: 'Amnesia',
  AuroraBeam: 'AuroraBeam',
  Barrage: 'Barrage',
  Barrier: 'Barrier',
  Bide: 'Bide',
  Bind: 'Bind',
  Bite: 'Bite',
  Blizzard: 'Blizzard',
  BodySlam: 'BodySlam',
  BoneClub: 'BoneClub',
  BoneBoomerang: 'BoneBoomerang',
  Bubble: 'Bubble',
  BubbleBeam: 'BubbleBeam',
  Clamp: 'Clamp',
  CometPunch: 'CometPunch',
  ConfuseRay: 'ConfuseRay',
  Confusion: 'Confusion',
  Constrict: 'Constrict',
  Conversion: 'Conversion',
  Counter: 'Counter',
  CrabHammer: 'CrabHammer',
  Cut: 'Cut',
  DefenseCurl: 'DefenseCurl',
  Dig: 'Dig',
  Disable: 'Disable',
  DizzyPunch: 'DizzyPunch',
  DoubleEdge: 'DoubleEdge',
  DoubleKick: 'DoubleKick',
  DoubleSlap: 'DoubleSlap',
  DoubleTeam: 'DoubleTeam',
  DragonRage: 'DragonRage',
  DreamEater: 'DreamEater',
  DrillPeck: 'DrillPeck',
  Earthquake: 'Earthquake',
  EggBomb: 'EggBomb',
  Ember: 'Ember',
  Explosion: 'Explosion',
  FireBlast: 'FireBlast',
  FirePunch: 'FirePunch',
  FireSpin: 'FireSpin',
  Fissure: 'Fissure',
  Flamethrower: 'Flamethrower',
  Flash: 'Flash',
  Fly: 'Fly',
  FocusEnergy: 'FocusEnergy',
  FuryAttack: 'FuryAttack',
  FurySwipes: 'FurySwipes',
  Glare: 'Glare',
  Growl: 'Growl',
  Growth: 'Growth',
  Guillotine: 'Guillotine',
  Gust: 'Gust',
  Harden: 'Harden',
  Haze: 'Haze',
  Headbutt: 'Headbutt',
  HighJumpKick: 'HighJumpKick',
  HornAttack: 'HornAttack',
  HornDrill: 'HornDrill',
  HydroPump: 'HydroPump',
  HyperBeam: 'HyperBeam',
  HyperFang: 'HyperFang',
  Hypnosis: 'Hypnosis',
  IceBeam: 'IceBeam',
  IcePunch: 'IcePunch',
  JumpKick: 'JumpKick',
  KarateChop: 'KarateChop',
  Kinesis: 'Kinesis',
  LeechLife: 'LeechLife',
  LeechSeed: 'LeechSeed',
  Leer: 'Leer',
  Lick: 'Lick',
  LightScreen: 'LightScreen',
  LovelyKiss: 'LovelyKiss',
  LowKick: 'LowKick',
  Meditate: 'Meditate',
  MegaDrain: 'MegaDrain',
  MegaKick: 'MegaKick',
  MegaPunch: 'MegaPunch',
  Metronome: 'Metronome',
  Mimic: 'Mimic',
  Minimize: 'Minimize',
  MirrorMove: 'MirrorMove',
  Mist: 'Mist',
  NightShade: 'NightShade',
  PayDay: 'PayDay',
  Peck: 'Peck',
  PetalDance: 'PetalDance',
  PinMissile: 'PinMissile',
  PoisonGas: 'PoisonGas',
  PoisonPowder: 'PoisonPowder',
  PoisonSting: 'PoisonSting',
  Pound: 'Pound',
  PsychicBeam: 'PsychicBeam',
  Psychic: 'Psychic',
  PsychicWave: 'PsychicWave',
  QuickAttack: 'QuickAttack',
  Rage: 'Rage',
  RazorLeaf: 'RazorLeaf',
  RazorWind: 'RazorWind',
  Recover: 'Recover',
  Reflect: 'Reflect',
  Rest: 'Rest',
  Roar: 'Roar',
  RockSlide: 'RockSlide',
  RockThrow: 'RockThrow',
  RollingKick: 'RollingKick',
  SandAttack: 'SandAttack',
  Tackle: 'Tackle',
  Screech: 'Screech',
  SeismicToss: 'SeismicToss',
  SelfDestruct: 'SelfDestruct',
  Sharpen: 'Sharpen',
  Sing: 'Sing',
  SkullBash: 'SkullBash',
  SkyAttack: 'SkyAttack',
  Slam: 'Slam',
  Slash: 'Slash',
  SleepPowder: 'SleepPowder',
  Sludge: 'Sludge',
  Smog: 'Smog',
  Smokescreen: 'Smokescreen',
  SoftBoiled: 'SoftBoiled',
  SolarBeam: 'SolarBeam',
  SonicBoom: 'SonicBoom',
  SpikeCannon: 'SpikeCannon',
  Splash: 'Splash',
  Spore: 'Spore',
  Stomp: 'Stomp',
  Strength: 'Strength',
  StringShot: 'StringShot',
  Struggle: 'Struggle',
  StunSpore: 'StunSpore',
  Submission: 'Submission',
  Substitute: 'Substitute',
  SuperFang: 'SuperFang',
  Supersonic: 'Supersonic',
  Surf: 'Surf',
  Swift: 'Swift',
  SwordsDance: 'SwordsDance',
  TailWhip: 'TailWhip',
  TakeDown: 'TakeDown',
  Teleport: 'Teleport',
  Thrash: 'Thrash',
  Thunder: 'Thunder',
  ThunderPunch: 'ThunderPunch',
  TripleKick: 'TripleKick',
  ThunderShock: 'ThunderShock',
  ThunderWave: 'ThunderWave',
  Thunderbolt: 'Thunderbolt',
  Toxic: 'Toxic',
  Transform: 'Transform',
  TriAttack: 'TriAttack',
  TwinNeedle: 'TwinNeedle',
  VineWhip: 'VineWhip',
  ViseGrip: 'ViseGrip',
  Waterfall: 'Waterfall',
  Whirlwind: 'Whirlwind',
  WingAttack: 'WingAttack',
  Withdraw: 'Withdraw',
  Wrap: 'Wrap',
};

export const STORAGE_KEYS = {
  ACTIVE_SLOT: 'spellingmon_active_slot',
  SETTINGS: 'spellingmon_settings',
  SESSION: 'spellingmon_session', // Slot-dependent
};

export const SUPPORTED_LANGUAGES = [
  { code: 'en-US', name: 'English', flag: '🇺🇸', native: 'English' },
  { code: 'de-DE', name: 'German', flag: '🇩🇪', native: 'Deutsch' },
  { code: 'es-MX', name: 'Spanish', flag: '🇲🇽', native: 'Español' },
  { code: 'fr-FR', name: 'French', flag: '🇫🇷', native: 'Français' },
  { code: 'pt-BR', name: 'Portuguese', flag: '🇧🇷', native: 'Português' },
  { code: 'ru-RU', name: 'Russian', flag: '🇷🇺', native: 'Русский' },
  { code: 'zh-CN', name: 'Mandarin', flag: '🇨🇳', native: '普通话' },
  { code: 'ja-JP', name: 'Japanese', flag: '🇯🇵', native: '日本語' }
];

export const MENU_TABS = {
  PARTY: 'party',
  SPELLINGDEX: 'spellingdex',
  PROGRESS: 'progress',
  MAP: 'map',
  SETTINGS: 'settings',
};

export const NPC_TYPES = {
  MOM: 'mom',
  HEALER: 'healer',
  GYM_BOSS: 'gym_boss',
  TEAM_STORM: 'team_storm',
  RIVAL: 'rival',
};

export const INTERIORS = {
  WORLD: 'world',
  HOME_1F: 'home_1f',
  HOME_2F: 'home_2f',
  SPELLING_CENTER: 'spelling_center',
  GYM: 'gym',
};

export const SPAWN_POINTS = {
  HOME: { x: 1, y: 1, interior: INTERIORS.HOME_2F },
  SPELLING_CENTER: { x: 4, y: 4, interior: INTERIORS.SPELLING_CENTER }
};

export const GAME_STATES = {
  BOOTING: 'BOOTING',
  LANGUAGE_SELECT: 'LANGUAGE_SELECT',
  TTS_CHECK: 'TTS_CHECK',
  LANDING: 'LANDING',
  SAVE_SELECTION: 'SAVE_SELECTION',
  LOADING: 'LOADING',
  ONBOARDING: 'ONBOARDING',
  CHARACTER_CREATION: 'ONBOARDING.CHARACTER_CREATION',
  STARTER_SELECTION: 'ONBOARDING.STARTER_SELECTION',
  PLAY: 'PLAY',
  WORLD: 'PLAY.WORLD',
  MOVING: 'PLAY.MOVING',
  DIALOG: 'PLAY.DIALOG',
  TRAINER_APPROACH: 'PLAY.TRAINER_APPROACH',
  BATTLE: 'PLAY.BATTLE',
  BATTLE_INTRO: 'PLAY.BATTLE.INTRO',
  BATTLE_ACTION_SELECT: 'PLAY.BATTLE.ACTION_SELECT',
  BATTLE_MOVE_SELECT: 'PLAY.BATTLE.MOVE_SELECT',
  BATTLE_SWITCHING: 'PLAY.BATTLE.SWITCHING',
  BATTLE_SPELLING: 'PLAY.BATTLE.SPELLING',
  BATTLE_PLAYER_ATTACK: 'PLAY.BATTLE.PLAYER_ATTACK',
  BATTLE_ENEMY_SPELLING: 'PLAY.BATTLE.ENEMY_SPELLING',
  BATTLE_ENEMY_TURN: 'PLAY.BATTLE.ENEMY_TURN',
  BATTLE_WHITED_OUT: 'PLAY.BATTLE.WHITED_OUT',
  BATTLE_VICTORY: 'PLAY.BATTLE.VICTORY',
  BATTLE_RESULTS: 'PLAY.BATTLE.RESULTS',
  BATTLE_PARTY_FULL: 'PLAY.BATTLE.PARTY_FULL',
  BATTLE_LEARN_MOVE: 'PLAY.BATTLE.LEARN_MOVE',
  MENU: 'PLAY.MENU',
  EVOLUTION: 'PLAY.EVOLUTION',
  STORY_CUTSCENE: 'PLAY.STORY_CUTSCENE',
};

export const GAME_EVENTS = {
  START: 'START',
  SELECT_LANG: 'SELECT_LANG',
  VERIFIED: 'VERIFIED',
  CONFIRM: 'CONFIRM',
  BACK: 'BACK',
  SELECT_SLOT: 'SELECT_SLOT',
  COMPLETE: 'COMPLETE',
  ENCOUNTER: 'ENCOUNTER',
  OPEN_MENU: 'OPEN_MENU',
  CLOSE: 'CLOSE',
  EVOLVE: 'EVOLVE',
  LOGOUT: 'LOGOUT',
  ATTACK: 'ATTACK',
  CAPTURE: 'CAPTURE',
  SWITCH: 'SWITCH',
  RUN: 'RUN',
  CANCEL: 'CANCEL',
  SUBMIT: 'SUBMIT',
  AI_SUBMIT: 'AI_SUBMIT',
  CONTINUE: 'CONTINUE',
  REPLACE: 'REPLACE',
  RELEASE: 'RELEASE',
  FINISH: 'FINISH',
  NEXT_SCENE: 'NEXT_SCENE',
};
